server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy /influx => InfluxDB (replaces Vite proxy in dev)
    location /influx/ {
        proxy_pass http://influxdb:8086/;
        proxy_set_header Host $host;
    }
}