export type AlertType =
  | "theft"
  | "fall"
  | "parking_violation"
  | "low_battery"
  | "geofence_breach"
  | "sensor_fault"
  | "connectivity";

export type AlertSeverity = "low" | "medium" | "high" | "critical";

/**
 * An event-driven alert generated by a Node-RED detection rule.
 * Written to InfluxDB and surfaced in the Grafana Alerting dashboard.
 */
export interface Alert {
  /** UUID uniquely identifying this alert */
  alert_id: string;

  /** References BikeDevice.bike_id */
  bike_id: string;

  /** ISO 8601 timestamp when the alert was generated */
  timestamp: string;

  /** Category of the alert */
  type: AlertType;

  /** How urgent the alert is */
  severity: AlertSeverity;

  /** Human-readable description shown in the dashboard */
  message: string;

  /** Whether an operator has acknowledged and seen this alert */
  acknowledged: boolean;
}
