/**
 * Computed summary of a completed trip.
 * Generated by Node-RED when a bike docks or remains stationary for an extended period.
 */
export interface TripRecord {
  /** UUID uniquely identifying this trip */
  trip_id: string;

  /** References BikeDevice.bike_id */
  bike_id: string;

  /** ISO 8601 timestamp when the trip started (bike unlocked / undocked) */
  start_time: string;

  /** ISO 8601 timestamp when the trip ended (bike locked / docked) */
  end_time: string;

  /** GPS coordinates at trip start */
  start_lat: number;
  start_lng: number;

  /** GPS coordinates at trip end */
  end_lat: number;
  end_lng: number;

  /** Total distance in km, computed as Haversine sum over the GPS trace */
  distance_km: number;

  /** Average speed over the trip in km/h */
  avg_speed_kmh: number;

  /** Peak speed recorded during the trip in km/h */
  max_speed_kmh: number;

  /** Total trip duration in minutes */
  duration_minutes: number;
}
